### ISSUE TITLE
 following files are missing in your kit

### ISSUE THREAD

**Issue by toonamo** [njh/perl-net-sdp#1]
When i attempt to run the perl script Build.PL i get the following error

perl Build.PL
WARNING: the following files are missing in your kit:
        Makefile.PL
        META.yml
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Net-SDP' version '0.07'

still seemed to build and install okay

**Comment by njh** [comment]
Those files are generated as part of the packaging process, you can download a pre-built copy from CPAN:
http://search.cpan.org/CPAN/authors/id/N/NJ/NJH/Net-SDP-0.07.tar.gz
