### ISSUE TITLE
NO makefile or META

### ISSUE THREAD

**Issue by n0pad** [njh/perl-net-sdp#2]
WARNING: the following files are missing in your kit:
        Makefile.PL
        META.yml
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Net-SDP' version '0.07'

**Comment by njh** [comment]
Something has changed since I last worked on this.
I will take a look.

**Comment by n0pad** [comment]
When Should i have a good answer about this?

**Comment by njh** [comment]
This is only a problem when building from the Git sources.

If you use CPAN or download the tarball, it should work fine:
http://search.cpan.org/CPAN/authors/id/N/NJ/NJH/Net-SDP-0.07.tar.gz

**Comment by n0pad** [comment]
Hm
